name: Generate PDF via Typst (Official Docker)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/typst:latest
      options: --user root # 権限エラーを防ぐ

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Noto CJK fonts (if missing)
        run: |
          # try apk (alpine) then apt (debian/ubuntu)
          if command -v apk >/dev/null 2>&1; then
            apk add --no-cache font-noto-cjk font-noto
          else
            apt-get update
            apt-get install -y --no-install-recommends fonts-noto-cjk fonts-noto
            rm -rf /var/lib/apt/lists/*
          fi
          fc-cache -f || true
          fc-list :family | grep -i noto || true
          
      - name: Verify typst and pandoc
        run: |
          which typst || true
          typst --version || true
          pandoc --version || true

      - name: Generate PDF
        run: |
          sed -i 's/\.pdf)/.png)/g' mnscrpt.md
          pandoc mnscrpt.md \
            -o mnscrpt.pdf \
            --pdf-engine=typst \
            --template=templates/custom.typ \
            --filter pandoc-crossref \
            --citeproc \
            --number-sections \
            --bibliography="refs/refs.bib" \
            --csl="refs/aip.csl" \
            --metadata-file <(echo "abstract-title: ''") \
            -M "figPrefix:Fig." \
            -M "eqnPrefix:Eq."

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: manuscript-pdf
          path: mnscrpt.pdf
